baseURL: "https://example.org"
languageCode: "en-us"
title: "Hugo Profile"
theme: "hugo-profile-1"

Paginate: 3
disqusShortname: gurusabarish
googleAnalytics: G-DWJJVE27WD

markup:
  goldmark:
    renderer:
      unsafe: true

# Menus:
#   main:
    # - identifier: blog
    #   name: Blog
    #   title: Blog posts
    #   url: /blogs
    #   weight: 1

    #Dropdown menu
    # - identifier: dropdown
    #   title: Example dropdown menu
    #   name: Dropdown
    #   weight: 2
    # - identifier: dropdown1
    #   title: example dropdown 1
    #   name: example 1
    #   url: /#
    #   parent: dropdown
    #   weight: 1
    # - identifier: dropdown2
    #   title: example dropdown 2
    #   name: example 2
    #   url: /#
    #   parent: dropdown
    #   weight: 2

params:
  title: "Andrew Ng"
  description: Text about my cool site
  # staticPath: ""  # The path to serve the static files from
  favicon: "/images/a.jpg"

  theme:
    disableThemeToggle: false
    # defaultTheme: "light" # dark

  # font:
  #   fontSize: 1.5rem # default: 1rem
  #   fontWeight: 500 # default: 400
  #   lineHeight: 1 # default: 1.5
  #   textAlign: right # default: left

  # color preference
  # color:
  #   textColor:
  #   secondaryTextColor:
  #   backgroundColor:
  #   secondaryBackgroundColor:
  #   primaryColor:
  #   secondaryColor:

  #   darkmode:
  #     textColor:
  #     secondaryTextColor:
  #     backgroundColor:
  #     secondaryBackgroundColor:
  #     primaryColor:
  #     secondaryColor:

  # If you want to customize the menu, you can change it here
  # navbar:
  #   align: mx-auto # Left: ms-auto | center: mx-auto | right: me-auto | Default: ms-auto
  #   brandLogo: "/logo.png" # Logo for the brand | default is the favicon variable
  #   brandName: "Profile" # Brand name for the brand | default is the title variable

  #   menus:
  #     disableAbout: true
  #     disableExperience: true
  #     disableEducation: true
  #     disableProjects: true
  #     disableAchievements: true
  #     disableContact: true

  # Hero
  hero:
    enable: true
    intro: "Hi, my name is"
    title: "Andrew Ng."
    subtitle: "Undergraduate at the University of Pennsylvania "
    content: "Majoring in Systems Science and Engineering with minors in Statistics (Wharton) and Mathematics"
    image: /images/Andrew.jpeg
    button:
      enable: true
      name: "Resume"
      url: "https://drive.google.com/file/d/1keOLmE5cUeWV_Dp9aI5p60hLs_rMiwS3/view?usp=sharing"
    socialLinks:
      fontAwesomeIcons:
        - icon: fab fa-github
          url: https://github.com/ngving22
        - icon: fab fa-linkedin
          url: https://www.linkedin.com/in/andrew-ng-56255a211
      #customIcons:
       # - icon: /fav.png
       #   url: "https://example.com"

  # About
  about:
    enable: true
    title: "About Me"
    image: "/images/avatar.png"
    content: |-
      I am student in SEAS at the University of Pennsylvania passionate about data science, machine learning, and artificial intelligence. I have a background in computer science and mathematics, and I have strong interests in the tech and finance. 
  # I am currently working on a project that will be used to help people find the best way to get around the city.
    skills:
      enable: true
      title: "Here are a few technologies I've been working with recently:"
      items:
        - "Java"
        - "Python (Pandas, Numpy, Matplotlib, Sci-kit, CVXPY, TensorFlow, PyTorch"
        - "HTML"
        - "OCaml"
        - "React"
        - "NodeJS"
        - "SolidWorks"
        - "Fusion360"

  # Experience
  experience:
    enable: true
    items:
      # - job: "Senior Software Developer"
      # #  company: "Facebook"
      #   companyUrl: "https://example.com"
      #   date: "Jan 2022 - present"
      #   featuredLink:
      #     enable: true
      #     name: "View the project"
      #     url: "https://example.com"
      #   content: "I am currently working as a software developer at [example org.](https://example.com) in San Francisco, CA. I am currently working on a project that will be used to help people find the best way to get around the city."

      # - job: "Software Developer"
      # #  company: "Amazon"
      #   companyUrl: "https://example.com"
      #   date: "Sep 2020 - Dec 2021"
      #   featuredLink:
      #     enable: true
      #     url: "https://example.com"
      #   info:
      #     enable: true
      #     content: I worked as a software developer for more than one year in Amazon.
      #   content: |
      #     I am currently working as a software developer at [example org.](https://example.com) in San Francisco, CA. I am currently working on a project that will be used to help people find the best way to get around the city.

      #     - Lead backend developer for a product.
      #     - Created a frontend design for a product.
      
      - job: "Undegraduate Researcher"
        company: "Perelman School of Medicine"
        #companyUrl: "https://example.com"
        date: "Oct 2022 - Present"
        info:
          enable: true
        featuredLink:
          enable: true
          url: "https://www.med.upenn.edu/apps/faculty/index.php/g275/p9247599"
        content: |
          Applied machine learning/deep learning techniques to
          medical imaging for disease diagnosis, prognosis, and 
          cancer treatment monitoring

          Implemented existing machine learning algorithms to better 
          understand early hepatic fibrosis diagnosis


      - job: "Student Researcher"
        company: "University of Pennsylvania CIS Dpt"
        companyUrl: "https://example.com"
        date: "Mar 2022 - Present"
        info:
          enable: true
        featuredLink:
          enable: true
          url: "https://www.cis.upenn.edu/~fbrett/research.html"
        content: |
          Conducted blockchain research which involved sweeping Ethereum transaction data 
          from various NFT marketplaces using Python (inc. pandas, numPy, matplotlib) to find market 
          trends and analyze the stability of financial networks

          Utilized concepts from existing financial models, the research to-be-published
          aims to investigate optimal royalty rates for creators in the growing digital art market

      - job: "Data Analyst"
        company: "Daily Pennsylvanian"
        #companyUrl: "https://example.com"
        date: "Jan 2022 - Present"
        featuredLink:
          enable: true
          url: "https://www.thedp.com/"
        content: |
          Leverage modern tools and technologies to enhance the digital and data analytics capabilities of the DP


          Used Dash, Plotly, and Google Analytics to automate analytic reports for the company by hosting to dashboard website


          Working on long-term project of topic analysis using natural language processing analyses


      - job: "Materials Science Engineering Intern"
        company: "NAVAIR"
        # companyUrl: "https://www.cnic.navy.mil/regions/ndw/installations/nas_patuxent_river/om/tenant_commands/navair.html"
        date: "Jun 2021 - Aug 2021"
        featuredLink:
          enable: true
          url: https://www.cnic.navy.mil/regions/ndw/installations/nas_patuxent_river/om/tenant_commands/navair.html
        content: "Designing and Testing AM (additively manufactured) Coupons in an Environmental Chamber to measure moisture absorption qualities of ABS (acrylonitrile butadiene styrene) and PLA (polylactic acid) at specific infill densities."
  # Education
  education:
    enable: true
    # index: true
    items:
      - title: "Bachelor of Engineering in Systems Science and Engineering"
        school:
          name: "University of Pennsylvania"
          url: "https://example.org"
        date: "2021 - 2025"
        content: |-
          Activities: Daily Pennsylvanian (Data Analyst), Wharton Undergraduate Sports Business Club (Finance Committee), Penn Data Science Group (Kaggle Team), Penn Newman Society, Penn Pickup Soccer Club (Events Coordinator)


          Relavent Coursework: Daily Pennsylvanian (Data Analyst), 
                              Penn Data Science Group (Kaggle Team), 
                              Penn Blockchain (Investment/Research Team),
                              Wharton Undergraduate Sports Business Club (Finance Committee), 
                              Penn Data Science Group (Kaggle Team), 
                              Penn Newman Society, 
                              Penn Pickup Soccer Club (Events Coordinator)


        featuredLink:
          enable: false
          name: "My academic record"
          url: "https://example.com"
      - title: "High School"
        school:
          name: "Leonardtown High School"
          url: "https://schools.smcps.org/lhs/"
        date: "2017 - 2021"
        #GPA: "4.53 out of 5.0"
        content:  |-
          SAT: 1540,  National AP Scholar, National Merit Commended Student, National Piano Teacher's Giuld Award, Varsity Soccer (2021 Player of the Year), Varsity Track, Chamber Orchestra, Student Government, National Honor Society, Principal's Advisory Committee, MD State Music Theory Advanced Award
        #featuredLink:
        #  enable: true
        #  url: "https://example.com"

  # Achievements
  # achievements:
  #   enable: true
  #   items:
  #     - title: National AP Scholar
  #       content: I solved all problems with optimal solution.
  #       url: https://example.com
  #     - title: Facebook Hackathon Winner
  #       content: Developed a product using Artificial Intelligence.
  #     - title: Hugo Profile
  #       content: Developed a theme and getting 1K+ downloads per month.
  #       url: "https://github.com/gurusabarish/hugo-profile"
  #     - title: Microsoft Imagine Runner
  #       content: We are developed a product which can help others.
  #     - title: Google Summer of Code
  #       content: Contributed to a open source project.
  #       url: https://example.com

  # projects
  projects:
    enable: true
    items:
      - title: Daily Pennsylvanian Analytics
        content: Data analysis through Python and Google Colab to find trends in user data
        image: /images/DP.png
        featured:
          name: Demo
          #link: https://colab.research.google.com/drive/14liPFRKVD1axPStDSNXqubB3ln8L7Z6U
        # badges:
        #   - "Hugo"
        #   - "Bootstrap"
        #   - "Javascript"
        links:
          #- icon: fa fa-envelope
          #  url: mailto:?subject=Hugo%20Profile%20Template&body=Check%20it%20out:%20https%3a%2f%2fhugo-profile.netlify.app%2fblog%2fmarkdown-syntax%2f
          - icon: fab fa-github
            url: https://github.com/ngving22/Daily-Pennsylvanian-Analytics
         # - icon: fab fa-twitter
           # url: https://twitter.com/intent/tweet?text=Check+it+out:&url=https%3A%2F%2Fgithub.com%2Fgurusabarish%2Fhugo-profile

      # - title: Image Converter
      #   content: A web app to convert image to pdf, png to jpg, png to jpg and png to webp without database using django.
      #   image: /images/projects/converter.jpg
      #   featured:
      #     name: Demo
      #     link: https://django-converter.herokuapp.com
      #   # badges:
      #   #   - "Django"
      #   #   - "Bootstrap"
      #   links:
      #     - icon: fab fa-github
      #       url: https://github.com/gurusabarish/converter

      - title: "2048"
        content: My version of the very popular, online number game 2048. Built for CIS 110 class.
        image: /images/2048_0.png
        featured:
          #name: Demo V2
          #link: https://github.com/ngving22/2048_game
        # badges:
        #   - "Hugo"
        #   - "Bootstrap"
        #   - "Javascript"
        links:
          - icon: fab fa-github
            url: https://github.com/ngving22/2048_game
            
       - title: "Weather App"
        content: Allows users to grab relevant weather data via OpenWeather API. 
                 Built app using React and Node JS.
        image: /images/weather.jpg
        featured:
          #name: Demo V2
          #link: https://github.com/ngving22/2048_game
        # badges:
        #   - "Hugo"
        #   - "Bootstrap"
        #   - "Javascript"
        links:
          - icon: fab fa-github
            url: https://github.com/ngving22/Weather-App


  #Contact
  contact:
    enable: true
    content: My inbox is always open. Whether you have a question or just want to say hi, Iâ€™ll try my best to get back to you!
    email: ngaj@seas.upenn.edu
    btnName: Mail me

  footer:
    recentPosts: false
    socialNetworks:
      github: https://github.com/ngving22
      linkedin: https://www.linkedin.com/in/andrew-ng-56255a211
      # twitter: https://twitter.com
      # instagram: https://instagram.com
      # facebook: https://facebook.com
